# Generated by Django 5.0.6 on 2024-06-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='summery',
            new_name='summary',
        ),
    ]
